USE [master]
GO

/****** Object:  Database [DigitalXJackySql]    Script Date: 22/03/2016 13:15:18 ******/
CREATE DATABASE [DigitalXJackySql]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DigitalXJackySql', FILENAME = N'G:\AMES\SQL\SqlServer\FinalProject\DigitalXJackySql.mdf' , SIZE = 20480KB , MAXSIZE = UNLIMITED, FILEGROWTH = 20480KB ), 
 FILEGROUP [FGAddress1] 
( NAME = N'AddressData1', FILENAME = N'G:\AMES\SQL\SqlServer\FinalProject\AddressData1.ndf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 20480KB ),
( NAME = N'AddressData2', FILENAME = N'G:\AMES\SQL\SqlServer\FinalProject\AddressData2.ndf' , SIZE = 10240KB , MAXSIZE = UNLIMITED, FILEGROWTH = 20480KB ), 
 FILEGROUP [FGCommodity1] 
( NAME = N'CommodityData1', FILENAME = N'G:\AMES\SQL\SqlServer\FinalProject\CommodityData1.ndf' , SIZE = 20480KB , MAXSIZE = UNLIMITED, FILEGROWTH = 30720KB ),
( NAME = N'CommodityData2', FILENAME = N'G:\AMES\SQL\SqlServer\FinalProject\CommodityData2.ndf' , SIZE = 20480KB , MAXSIZE = UNLIMITED, FILEGROWTH = 30720KB ), 
 FILEGROUP [FGCustomer1] 
( NAME = N'CustomerData1', FILENAME = N'G:\AMES\SQL\SqlServer\FinalProject\CustomerData1.ndf' , SIZE = 20480KB , MAXSIZE = UNLIMITED, FILEGROWTH = 30720KB ),
( NAME = N'CustomerData2', FILENAME = N'G:\AMES\SQL\SqlServer\FinalProject\CustomerData2.ndf' , SIZE = 20480KB , MAXSIZE = UNLIMITED, FILEGROWTH = 30720KB ), 
 FILEGROUP [FGMist1] 
( NAME = N'Mist1Data', FILENAME = N'G:\AMES\SQL\SqlServer\FinalProject\Mist1Data.ndf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 5120KB ), 
 FILEGROUP [FGOrder1] 
( NAME = N'OrderData1', FILENAME = N'G:\AMES\SQL\SqlServer\FinalProject\OrderData1.ndf' , SIZE = 20480KB , MAXSIZE = UNLIMITED, FILEGROWTH = 30720KB ),
( NAME = N'OrderData2', FILENAME = N'G:\AMES\SQL\SqlServer\FinalProject\OrderData2.ndf' , SIZE = 20480KB , MAXSIZE = UNLIMITED, FILEGROWTH = 30720KB )
 LOG ON 
( NAME = N'DigitalXJackySql_log', FILENAME = N'G:\AMES\SQL\SqlServer\FinalProject\DigitalXJackySql_log.ldf' , SIZE = 10240KB , MAXSIZE = 2048GB , FILEGROWTH = 20480KB )
GO

ALTER DATABASE [DigitalXJackySql] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DigitalXJackySql].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DigitalXJackySql] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DigitalXJackySql] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DigitalXJackySql] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DigitalXJackySql] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DigitalXJackySql] SET ARITHABORT OFF 
GO

ALTER DATABASE [DigitalXJackySql] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DigitalXJackySql] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DigitalXJackySql] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DigitalXJackySql] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DigitalXJackySql] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DigitalXJackySql] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DigitalXJackySql] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DigitalXJackySql] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DigitalXJackySql] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DigitalXJackySql] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DigitalXJackySql] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DigitalXJackySql] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DigitalXJackySql] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DigitalXJackySql] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DigitalXJackySql] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DigitalXJackySql] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DigitalXJackySql] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DigitalXJackySql] SET RECOVERY FULL 
GO

ALTER DATABASE [DigitalXJackySql] SET  MULTI_USER 
GO

ALTER DATABASE [DigitalXJackySql] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DigitalXJackySql] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DigitalXJackySql] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DigitalXJackySql] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DigitalXJackySql] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DigitalXJackySql] SET  READ_WRITE 
GO


